name: test-flow

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run dev
    
